export const ratchets: OptionBey[] = [
  { id: 1, label: "0-80" },
  { id: 2, label: "1-60" },
  { id: 3, label: "1-80" },
  { id: 4, label: "2-60" },
  { id: 5, label: "2-70" },
  { id: 6, label: "2-80" },
  { id: 7, label: "3-60" },
  { id: 8, label: "3-70" },
  { id: 9, label: "3-80" },
  { id: 10, label: "3-85" },
  { id: 11, label: "4-55" },
  { id: 12, label: "4-60" },
  { id: 13, label: "4-70" },
  { id: 14, label: "4-80" },
  { id: 15, label: "5-60" },
  { id: 16, label: "5-70" },
  { id: 17, label: "5-80" },
  { id: 18, label: "6-60" },
  { id: 19, label: "6-80" },
  { id: 20, label: "7-60" },
  { id: 21, label: "7-70" },
  { id: 22, label: "7-80" },
  { id: 23, label: "9-60" },
  { id: 24, label: "9-70" },
  { id: 25, label: "9-80" },
];

export const bits: OptionBey[] = [
  { id: 1, label: "Flat (F)" },
  { id: 2, label: "Taper (T)" },
  { id: 3, label: "Ball (B)" },
  { id: 4, label: "Needle (N)" },
  { id: 5, label: "High Needle (HN)" },
  { id: 6, label: "Low Flat (LF)" },
  { id: 7, label: "Point (P)" },
  { id: 8, label: "Orb (O)" },
  { id: 9, label: "Rush (R)" },
  { id: 10, label: "High Taper (HT)" },
  { id: 11, label: "Spike (S)" },
  { id: 12, label: "Gear Flat (GF)" },
  { id: 13, label: "Gear Ball (GB)" },
  { id: 14, label: "Gear Point (GP)" },
  { id: 15, label: "Gear Needle (GN)" },
  { id: 16, label: "Accel (A)" },
  { id: 17, label: "Disc Ball (DB)" },
  { id: 18, label: "Hexa (H)" },
  { id: 19, label: "Quake (Q)" },
  { id: 20, label: "Metal Needle (MN)" },
  { id: 21, label: "Unite (U)" },
  { id: 22, label: "Cyclone (C)" },
  { id: 23, label: "Dot (D)" },
  { id: 24, label: "Glide (G)" },
  { id: 25, label: "Elevate (E)" },
  { id: 26, label: "Free Ball (FB)" },
  { id: 27, label: "Bound Spike (BS)" },
  { id: 28, label: "Rubber Accel (RA)" },
  { id: 29, label: "Level (L)" },
  { id: 30, label: "Trans Point (TP)" },
  { id: 31, label: "Low Rush (LR)" },
  { id: 32, label: "Under Needle (UN)" },
];

export const blades: OptionBey[] = [
  { id: 1, label: "BlackShell - Obsidian Shell" },
  { id: 2, label: "CobaltDragoon" },
  { id: 3, label: "CobaltDrake" },
  { id: 4, label: "CrimsonGaruda - Scarlet Garuda" },
  { id: 5, label: "DranDagger - Dagger Dran" },
  { id: 6, label: "DranSword - Sword Dran" },
  { id: 7, label: "HellsChain - Chain Incendio" },
  { id: 8, label: "HellsScythe - Scythe Incendio" },
  { id: 9, label: "KnightLance - Lance Knight" },
  { id: 10, label: "KnightShield - Helm Knight" },
  { id: 11, label: "LeonClaw - Claw Leon" },
  { id: 12, label: "PhoenixFeather - Feather Phoenix" },
  { id: 13, label: "PhoenixWing - Soar Phoenix" },
  { id: 14, label: "RhinoHorn - Horn Rhino" },
  { id: 15, label: "SharkEdge - Keel Shark" },
  { id: 16, label: "ShelterDrake" },
  { id: 17, label: "SphinxCowl - Cowl Sphinx" },
  { id: 18, label: "TyrannoBeat - Beat Tyranno" },
  { id: 19, label: "UnicornSting - Sting Unicorn" },
  { id: 20, label: "ViperTail - Tail Viper" },
  { id: 21, label: "WeissTiger - Pearl Tiger" },
  { id: 22, label: "WhaleWave - Tide Whale" },
  { id: 23, label: "WizardArrow - Arrow Wizard" },
  { id: 24, label: "WyvernGale - Gale Wyvern" },
  { id: 25, label: "CrocCrunch - Bite Croc" },
  { id: 26, label: "Gill Shark" },
  { id: 27, label: "ShinobiKnife - Knife Shinobi" },
  { id: 28, label: "TyrannoRoar - Roar Tyranno" },
  { id: 29, label: "BearScratch - Savage Bear" },
  { id: 30, label: "SamuraiSteel - Steel Samurai" },
  { id: 31, label: "PteraSwing - Talon Ptera" },
  { id: 32, label: "MammothTusk - Tusk Mammoth" },
  { id: 33, label: "Yell Kong" },
  { id: 34, label: "DragoonStorm" },
  { id: 35, label: "DranzerSpiral" },
  { id: 36, label: "DrigerSlash" },
  { id: 37, label: "DracielShield" },
  { id: 38, label: "Lightning L-Drago" },
  { id: 39, label: "StormPegasis - Storm Pegasis" },
  { id: 40, label: "VictoryValkyrie - Victory Valtryek" },
  { id: 41, label: "XenoXcalibur - Xeno Xcalius" },
  { id: 42, label: "Mosasaurus" },
  { id: 43, label: "Quetzalcoatlus" },
  { id: 44, label: "Spinosaurus" },
  { id: 45, label: "T. Rex" },
  { id: 46, label: "Captain America" },
  { id: 47, label: "Iron Man" },
  { id: 48, label: "Red Hulk" },
  { id: 49, label: "Spider-Man" },
  { id: 50, label: "Thanos" },
  { id: 51, label: "Venom" },
  { id: 52, label: "Darth Vader" },
  { id: 53, label: "General Grievous" },
  { id: 54, label: "Luke Skywalker" },
  { id: 55, label: "Moff Gideon" },
  { id: 56, label: "Obi-Wan Kenobi" },
  { id: 57, label: "The Mandalorian" },
  { id: 58, label: "Megatron" },
  { id: 59, label: "Optimus Primal" },
  { id: 60, label: "Optimus Prime" },
  { id: 61, label: "Starscream" },
  { id: 62, label: "DranBuster" },
  { id: 63, label: "HellsHammer" },
  { id: 64, label: "WizardRod" },
  { id: 65, label: "ShinobiShadow" },
  { id: 66, label: "LeonCrest" },
  { id: 67, label: "PhoenixRudder" },
  { id: 68, label: "SilverWolf" },
  { id: 69, label: "SamuraiSaber" },
  { id: 70, label: "ImpactDrake" },
  { id: 71, label: "KnightMail" },
  { id: 72, label: "GhostCircle" },
  { id: 73, label: "GolemRock" },
];

export const photos: string[] = [
  "BearScratch - Savage Bear",
  "BlackShell - Obsidian Shell",
  "CobaltDragoon",
  "ImpactDrake",
  "KnightLance - Lance Knight",
  "KnightMail",
  "ShinobiShadow",
  "SilverWolf",
  "SphinxCowl",
  "Cowl Sphinx",
  "CobaltDrake",
  "CrimsonGaruda - Scarlet Garuda",
  "DracielShield",
  "KnightShield - Helm Knight",
  "LeonClaw - Claw Leon",
  "LeonCrest",
  "TyrannoBeat - Beat Tyranno",
  "UnicornSing - Sting Unicorn",
  "ViperTail - Tail Viper",
  "DranBuster",
  "DranDagger - Dagger Dran",
  "DranSword - Sword Dran",
  "Lightning L-Drago",
  "Nolmage",
  "PhoenixFeather - Feather Phoenix",
  "WhaleWave - Tide Whale",
  "WizardArrow  - rrow Wizard",
  "WeissTiger - Pearl Tiger",
  "DranSword - Sword Dran",
  "DranzerSpiral",
  "DrigerSlash",
  "PhoenixFeather - Feather Phoenix",
  "PhoenixRudder",
  "PhoenixWing - Soar Phoenix",
  "WizardArrow - Arrow Wizard",
  "WizardRod",
  "WyvernGale - Gale Wyvern",
  "GhostCircle",
  "GolemRock",
  "HellChain - Chain Incendio",
  "HellsHammer",
  "HellsScythe - Scythe Incendio",
  "PteraSwing - Talon Ptera",
  "RhinoHorn - Horn Rhino",
  "SamuraiSaber",
  "SharkEdge - Keel Shark",
  "ShelterDrake",
];
